-- Squad Goals / Trip Ledger - Supabase schema
-- The *_sheet tables intentionally preserve the original Google Sheet column order.
-- Import the old spreadsheet values into these columns without changing their meaning.

create extension if not exists pgcrypto;

create table if not exists settings_sheet (
  row_number integer primary key,
  col_a text,
  col_b text,
  col_c text,
  col_d text,
  col_e text,
  col_f text,
  col_g text,
  col_h text,
  col_i text,
  col_j text,
  col_k text,
  col_l text,
  col_m text,
  col_n text,
  col_o text,
  col_p text,
  col_q text,
  col_r text,
  col_s text,
  col_t text,
  col_u text,
  col_v text,
  col_w text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists transactions_sheet (
  id bigint generated by default as identity primary key,
  col_a text not null,
  col_b timestamptz,
  col_c numeric(14,2) not null default 0,
  col_d text,
  col_e text,
  col_f text,
  col_g timestamptz not null default now(),
  col_h text,
  col_i text,
  col_j text default 'Verified',
  created_at timestamptz not null default now()
);
create unique index if not exists transactions_utr_idx on transactions_sheet(col_a);
create index if not exists transactions_date_idx on transactions_sheet(col_b desc);
create index if not exists transactions_claimant_idx on transactions_sheet(col_i);
create index if not exists transactions_status_idx on transactions_sheet(col_j);

create table if not exists members_sheet (
  id bigint generated by default as identity primary key,
  col_a text,
  col_b text,
  col_c text,
  col_d text,
  col_e text,
  col_f text,
  col_g text,
  col_h text,
  col_i text,
  col_j text,
  col_k text,
  col_l text,
  col_m text,
  col_n text,
  col_o text,
  col_p text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists members_name_idx on members_sheet(col_a);
create index if not exists members_pin_idx on members_sheet(col_d);

create table if not exists member_sheet_meta (
  id bigint primary key default 1,
  coordinator_bg text,
  member_bg text,
  chief_coordinator_signature text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists places_sheet (
  id bigint generated by default as identity primary key,
  col_a text,
  col_b text,
  col_c text default 'Pending',
  col_d timestamptz,
  col_e text,
  col_f text,
  col_g date,
  col_h time,
  col_i text,
  col_j text,
  col_k timestamptz,
  col_l text,
  created_at timestamptz not null default now()
);
create index if not exists places_status_idx on places_sheet(col_c);
create index if not exists places_trip_day_idx on places_sheet(col_f);

create table if not exists budget_sheet (
  id bigint generated by default as identity primary key,
  col_a text,
  col_b numeric(14,2) default 0,
  created_at timestamptz not null default now()
);
create index if not exists budget_category_idx on budget_sheet(col_a);

create table if not exists messages_sheet (
  id bigint generated by default as identity primary key,
  col_a timestamptz not null default now(),
  col_b text,
  col_c text,
  created_at timestamptz not null default now()
);
create index if not exists messages_timestamp_idx on messages_sheet(col_a desc);
create index if not exists messages_id_idx on messages_sheet(id desc);

create table if not exists archives_sheet (
  id bigint generated by default as identity primary key,
  col_a text,
  col_b text,
  col_c text,
  col_d text,
  col_e text,
  created_at timestamptz not null default now()
);
create index if not exists archives_name_idx on archives_sheet(col_a);

create table if not exists app_meta (
  id bigint primary key default 1,
  security_status text default '',
  default_secure_avatar text default 'https://ui-avatars.com/api/?name=U&background=cbd5e1&color=ffffff',
  trip_timezone text default 'Asia/Kolkata',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Storage bucket used for signatures, images, PDFs and other trip assets.
insert into storage.buckets (id, name, public)
values ('trip-assets', 'trip-assets', false)
on conflict (id) do update set public = false;

-- RLS: the browser never talks directly to Supabase in this migration.
-- The Vercel API uses the service-role key, which bypasses RLS.
alter table settings_sheet enable row level security;
alter table transactions_sheet enable row level security;
alter table members_sheet enable row level security;
alter table member_sheet_meta enable row level security;
alter table places_sheet enable row level security;
alter table budget_sheet enable row level security;
alter table messages_sheet enable row level security;
alter table archives_sheet enable row level security;
alter table app_meta enable row level security;

-- Storage policies are deliberately restrictive. Server-side service-role access is used.
drop policy if exists "trip assets authenticated read" on storage.objects;
create policy "trip assets authenticated read"
on storage.objects for select
to authenticated
using (bucket_id = 'trip-assets');

drop policy if exists "trip assets authenticated upload" on storage.objects;
create policy "trip assets authenticated upload"
on storage.objects for insert
to authenticated
with check (bucket_id = 'trip-assets');

drop policy if exists "trip assets authenticated update" on storage.objects;
create policy "trip assets authenticated update"
on storage.objects for update
to authenticated
using (bucket_id = 'trip-assets')
with check (bucket_id = 'trip-assets');

drop policy if exists "trip assets authenticated delete" on storage.objects;
create policy "trip assets authenticated delete"
on storage.objects for delete
to authenticated
using (bucket_id = 'trip-assets');

-- Seed rows matching the GAS defaults.
insert into settings_sheet (row_number, col_a, col_b)
values (1, 'DASHBOARD', '10000')
on conflict (row_number) do nothing;

insert into member_sheet_meta (id)
values (1)
on conflict (id) do nothing;

insert into app_meta (id)
values (1)
on conflict (id) do nothing;
